// ─── DB Schema Types ─────────────────────────────────────────────────────────
// These mirror docs/DB-SCHEMA.md table definitions
// Full ORM models to be generated by Drizzle / Prisma in apps/api

export interface DbUser {
  id: string
  email: string | null
  walletAddress: string
  role: 'operator' | 'viewer' | 'admin'
  createdAt: Date
  updatedAt: Date
}

export interface DbMaskedAccount {
  id: string
  userId: string
  chain: string
  address: string
  label: string | null
  lethalityTier: 'high' | 'mid' | 'dust'
  lastScoutedAt: Date | null
  createdAt: Date
}

export interface DbExtractionLane {
  id: string
  maskedAccountId: string
  status: string
  chain: string
  assetAddress: string | null
  assetSymbol: string
  amountRaw: string
  amountUsd: number
  signatureExpiry: number | null
  relayer: string | null
  ghostLane: string | null
  retryCount: number
  createdAt: Date
  updatedAt: Date
}

export interface DbSentinelRun {
  id: string
  laneId: string
  sentinel: string
  action: string
  status: 'started' | 'completed' | 'failed'
  durationMs: number | null
  error: string | null
  createdAt: Date
}

export interface DbPolicy {
  id: string
  name: string
  scope: 'global' | 'chain' | 'wallet'
  scopeValue: string | null
  rule: Record<string, unknown>
  active: boolean
  createdAt: Date
  updatedAt: Date
}
